### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by lsyysl9711** [TreezzZ/MyDevEnv#1]
Whay do you create this repo? 

I am curious!

**Comment by TreezzZ** [comment]
> 

Thanks for being interesting in this repo!

Because recently I often write codes on different machines, I need a script to build my development environment quickly.

This repo contains Dockerfile (I can use one command to build PyTorch, Cuda, and so on) and install.sh & init.vim (Configurations of zsh and neovim, because I usually use vim to write codes on remote machines).

If you have any others questions, feel free to contact me.
